import React, { useState, useEffect } from 'react';
import api from '../../api';

const STATUS_COLORS = { draft: 'badge-draft', sent: 'badge-sent', paid: 'badge-paid', overdue: 'badge-overdue', cancelled: 'badge-inactive' };

export default function MyInvoices() {
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [viewInvoice, setViewInvoice] = useState(null);

  const load = () => api.get('/api/invoices').then(r => setInvoices(r.data)).finally(() => setLoading(false));
  useEffect(load, []);

  const handleView = async (inv) => {
    const r = await api.get(`/api/invoices/${inv.id}`);
    setViewInvoice(r.data);
  };

  const printInvoice = (invoice) => {
    const win = window.open('', '_blank');
    win.document.write(`
      <html><head><title>Invoice ${invoice.invoice_number}</title>
      <style>
        body { font-family: sans-serif; padding: 40px; color: #111; max-width: 800px; margin: 0 auto; }
        .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
        .logo { font-size: 24px; font-weight: bold; color: #2563eb; }
        h2 { color: #6b7280; font-weight: normal; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; }
        table { width: 100%; border-collapse: collapse; margin-top: 24px; }
        th { text-align: left; border-bottom: 2px solid #e5e7eb; padding: 10px 8px; font-size: 12px; color: #6b7280; text-transform: uppercase; }
        td { padding: 10px 8px; border-bottom: 1px solid #f3f4f6; font-size: 13px; }
        .total-row { font-weight: bold; font-size: 16px; text-align: right; margin-top: 20px; padding-top: 16px; border-top: 2px solid #e5e7eb; }
        .status-badge { display: inline-block; padding: 4px 10px; border-radius: 999px; font-size: 11px; font-weight: 600; text-transform: uppercase; background: #dcfce7; color: #166534; }
      </style></head>
      <body>
        <div class="header">
          <div>
            <div class="logo">Flow</div>
            <p style="color:#6b7280;font-size:13px;margin-top:4px">Workforce Platform</p>
          </div>
          <div style="text-align:right">
            <div style="font-size:20px;font-weight:bold;color:#111">${invoice.invoice_number}</div>
            <span class="status-badge">${invoice.status}</span>
            ${invoice.due_date ? `<p style="color:#6b7280;font-size:12px;margin-top:8px">Due: ${invoice.due_date}</p>` : ''}
          </div>
        </div>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-bottom:30px">
          <div>
            <h2>FROM</h2>
            <p style="font-weight:600;font-size:15px;margin:4px 0">${invoice.candidate_name}</p>
            <p style="color:#6b7280;font-size:13px">${invoice.candidate_email || ''}</p>
            <p style="color:#6b7280;font-size:13px">${invoice.candidate_role || ''}</p>
          </div>
          <div>
            <h2>TO</h2>
            <p style="font-weight:600;font-size:15px;margin:4px 0">${invoice.client_name || 'N/A'}</p>
            <p style="color:#6b7280;font-size:13px">${invoice.client_email || ''}</p>
            <p style="color:#6b7280;font-size:13px">${(invoice.client_address || '').replace(/\n/g, '<br/>')}</p>
          </div>
        </div>
        <div style="background:#f9fafb;padding:12px 16px;border-radius:8px;margin-bottom:20px">
          <p style="font-size:13px;margin:0;color:#374151"><strong>Period:</strong> ${invoice.period_start} to ${invoice.period_end} &nbsp;·&nbsp; <strong>Rate:</strong> $${invoice.hourly_rate}/hr</p>
        </div>
        <table>
          <thead><tr><th>Date</th><th>Description</th><th>Hours</th><th>Rate</th><th style="text-align:right">Amount</th></tr></thead>
          <tbody>
            ${(invoice.line_items || []).map(li => `
              <tr>
                <td>${li.date}</td>
                <td style="color:#6b7280">${li.description || ''}</td>
                <td>${li.hours}h</td>
                <td>$${li.rate}</td>
                <td style="text-align:right">$${li.amount.toFixed(2)}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        <div class="total-row">Total Amount: $${invoice.total_amount.toLocaleString('en-US', { minimumFractionDigits: 2 })}</div>
        <p style="margin-top:40px;font-size:12px;color:#9ca3af;text-align:center">Generated by Flow · Thank you for your work!</p>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  const totalPaid = invoices.filter(i => i.status === 'paid').reduce((s, i) => s + i.total_amount, 0);
  const totalPending = invoices.filter(i => ['sent', 'draft'].includes(i.status)).reduce((s, i) => s + i.total_amount, 0);

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900">My Invoices</h1>
        <p className="text-gray-500 mt-1">{invoices.length} invoices · ${totalPaid.toLocaleString('en-US', { maximumFractionDigits: 0 })} received · ${totalPending.toLocaleString('en-US', { maximumFractionDigits: 0 })} pending</p>
      </div>

      {/* Summary */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        <div className="card p-4 text-center">
          <p className="text-2xl font-bold text-green-600">${totalPaid.toLocaleString('en-US', { maximumFractionDigits: 0 })}</p>
          <p className="text-xs text-gray-500 mt-1">Total Received</p>
        </div>
        <div className="card p-4 text-center">
          <p className="text-2xl font-bold text-emerald-600">${totalPending.toLocaleString('en-US', { maximumFractionDigits: 0 })}</p>
          <p className="text-xs text-gray-500 mt-1">Pending Payment</p>
        </div>
        <div className="card p-4 text-center">
          <p className="text-2xl font-bold text-gray-900">{invoices.length}</p>
          <p className="text-xs text-gray-500 mt-1">Total Invoices</p>
        </div>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-16"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-emerald-600"></div></div>
      ) : invoices.length === 0 ? (
        <div className="card text-center py-16 text-gray-400">
          <div className="text-4xl mb-2">📄</div>
          <p>No invoices yet</p>
          <p className="text-sm mt-1">Your invoices will appear here once generated by admin</p>
        </div>
      ) : (
        <div className="card overflow-hidden">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 border-b border-gray-100">
              <tr>
                <th className="text-left px-4 py-3 text-gray-500 font-medium">Invoice #</th>
                <th className="text-left px-4 py-3 text-gray-500 font-medium">Period</th>
                <th className="text-left px-4 py-3 text-gray-500 font-medium">Client</th>
                <th className="text-left px-4 py-3 text-gray-500 font-medium">Hours</th>
                <th className="text-left px-4 py-3 text-gray-500 font-medium">Amount</th>
                <th className="text-left px-4 py-3 text-gray-500 font-medium">Due Date</th>
                <th className="text-left px-4 py-3 text-gray-500 font-medium">Status</th>
                <th className="text-right px-4 py-3 text-gray-500 font-medium">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {invoices.map(inv => (
                <tr key={inv.id} className="hover:bg-gray-50">
                  <td className="px-4 py-3 font-mono text-emerald-600 font-medium">{inv.invoice_number}</td>
                  <td className="px-4 py-3 text-gray-600 text-xs">{inv.period_start}<br />{inv.period_end}</td>
                  <td className="px-4 py-3 text-gray-500">{inv.client_name || '—'}</td>
                  <td className="px-4 py-3 text-gray-700">{inv.total_hours}h</td>
                  <td className="px-4 py-3 font-bold text-gray-900">${inv.total_amount.toLocaleString('en-US', { minimumFractionDigits: 2 })}</td>
                  <td className="px-4 py-3 text-gray-500">{inv.due_date || '—'}</td>
                  <td className="px-4 py-3"><span className={STATUS_COLORS[inv.status]}>{inv.status}</span></td>
                  <td className="px-4 py-3 text-right">
                    <div className="flex items-center justify-end gap-2">
                      <button onClick={() => handleView(inv)} className="text-emerald-600 hover:underline text-xs">View</button>
                      <button onClick={() => handleView(inv).then(() => {})} className="text-gray-500 hover:underline text-xs">Print</button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Invoice Detail Modal */}
      {viewInvoice && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between px-6 py-4 border-b">
              <h3 className="font-semibold text-gray-900 text-lg">{viewInvoice.invoice_number}</h3>
              <div className="flex items-center gap-2">
                <button onClick={() => printInvoice(viewInvoice)} className="btn-secondary text-sm py-1.5">🖨️ Print</button>
                <button onClick={() => setViewInvoice(null)} className="text-gray-400 hover:text-gray-600 text-xl">✕</button>
              </div>
            </div>
            <div className="p-6 space-y-4">
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div className="bg-gray-50 p-3 rounded-lg">
                  <p className="text-gray-500 text-xs mb-1">Client</p>
                  <p className="font-medium">{viewInvoice.client_name || 'N/A'}</p>
                </div>
                <div className="bg-gray-50 p-3 rounded-lg">
                  <p className="text-gray-500 text-xs mb-1">Period</p>
                  <p className="font-medium">{viewInvoice.period_start} → {viewInvoice.period_end}</p>
                </div>
                <div className="bg-emerald-50 p-3 rounded-lg">
                  <p className="text-blue-500 text-xs mb-1">Total Hours</p>
                  <p className="font-bold text-emerald-700">{viewInvoice.total_hours}h @ ${viewInvoice.hourly_rate}/hr</p>
                </div>
                <div className="bg-green-50 p-3 rounded-lg">
                  <p className="text-green-500 text-xs mb-1">Total Amount</p>
                  <p className="font-bold text-green-700 text-lg">${viewInvoice.total_amount.toLocaleString('en-US', { minimumFractionDigits: 2 })}</p>
                </div>
              </div>

              {viewInvoice.line_items?.length > 0 && (
                <div>
                  <h4 className="text-sm font-medium text-gray-700 mb-2">Time Breakdown</h4>
                  <div className="border border-gray-100 rounded-lg overflow-hidden">
                    <table className="w-full text-xs">
                      <thead className="bg-gray-50"><tr>
                        <th className="text-left px-3 py-2 text-gray-500">Date</th>
                        <th className="text-left px-3 py-2 text-gray-500">Description</th>
                        <th className="text-right px-3 py-2 text-gray-500">Hours</th>
                        <th className="text-right px-3 py-2 text-gray-500">Amount</th>
                      </tr></thead>
                      <tbody className="divide-y divide-gray-50">
                        {viewInvoice.line_items.map((li, i) => (
                          <tr key={i}>
                            <td className="px-3 py-2">{li.date}</td>
                            <td className="px-3 py-2 text-gray-500">{li.description}</td>
                            <td className="px-3 py-2 text-right font-medium">{li.hours}h</td>
                            <td className="px-3 py-2 text-right font-medium">${li.amount.toFixed(2)}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
